-- VHDL Entity sequential.edgeDetector.symbol
--
-- Created:
--          by - francois.users (Aphelia)
--          at - 08:37:10 01/16/15
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.1 (Build 12)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
LIBRARY gates;
  USE gates.gates.all;

ENTITY edgeDetector IS
   GENERIC( 
      delay : time := gateDelay
   );
   PORT( 
      clock      : IN     std_ulogic;
      in_asynch  : IN     std_ulogic;
      reset      : IN     std_ulogic;
      edge_pulse : OUT    std_ulogic
   );

-- Declarations

END edgeDetector ;

