-- VHDL Entity sequential.freqDivider.symbol
--
-- Created:
--          by - Everyone.UNKNOWN (WE5450)
--          at - 10:49:08 17-Nov-16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.2 (Build 5)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.numeric_std.all;
LIBRARY gates;
  USE gates.gates.all;

ENTITY freqDivider IS
   GENERIC( 
      divideValue : positive := 256;
      delay       : time     := gateDelay
   );
   PORT( 
      clock  : IN     std_ulogic;
      reset  : IN     std_ulogic;
      enable : OUT    std_ulogic
   );

-- Declarations

END freqDivider ;

