-- VHDL Entity Common_test.rotaryToUnsigned_tester.interface
--
-- Created:
--          by - francois.francois (Aphelia)
--          at - 11:54:00 11/07/19
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.1 (Build 12)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.numeric_std.all;

ENTITY rotaryToUnsigned_tester IS
   GENERIC( 
      rotaryBitNb : positive := 4;
      outputBitNb : positive := 6
   );
   PORT( 
      number : IN     unsigned (outputBitNb-1 DOWNTO 0);
      clock  : OUT    std_ulogic;
      reset  : OUT    std_ulogic;
      rotary : OUT    unsigned (rotaryBitNb-1 DOWNTO 0)
   );

-- Declarations

END rotaryToUnsigned_tester ;

