-- VHDL Entity Common.edgeDetector.symbol
--
-- Created:
--          by - francois.francois (Aphelia)
--          at - 17:10:33 10/02/19
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.1 (Build 12)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;

ENTITY edgeDetector IS
   PORT( 
      clock   : IN     std_ulogic;
      pulse   : IN     std_ulogic;
      reset   : IN     std_ulogic;
      falling : OUT    std_ulogic;
      rising  : OUT    std_ulogic
   );

-- Declarations

END edgeDetector ;

