-- VHDL Entity Common.rotaryToUnsigned.symbol
--
-- Created:
--          by - francois.francois (Aphelia)
--          at - 13:19:40 11/07/19
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.1 (Build 12)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.numeric_std.all;

ENTITY rotaryToUnsigned IS
   GENERIC( 
      rotaryBitNb  : positive := 4;
      outputBitNb  : positive := 8;
      counterBitNb : positive := 10E3
   );
   PORT( 
      clock  : IN     std_ulogic;
      reset  : IN     std_ulogic;
      number : OUT    unsigned (outputBitNb-1 DOWNTO 0);
      rotary : IN     unsigned (rotaryBitNb-1 DOWNTO 0)
   );

-- Declarations

END rotaryToUnsigned ;

