-- VHDL Entity OBC.Test.symbol
--
-- Created:
--          by - student.UNKNOWN (DESKTOP-3I0F3HP)
--          at - 16:21:08 16.06.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.numeric_std.all;

ENTITY Test IS
   PORT( 
      clock : IN     std_ulogic;
      reset : IN     std_ulogic;
      Led1  : OUT    std_logic
   );

-- Declarations

END Test ;

