-- VHDL Entity Board.obc_circuit.symbol
--
-- Created:
--          by - student.UNKNOWN (DESKTOP-3I0F3HP)
--          at - 10:32:08 14.07.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.numeric_std.all;

ENTITY obc_circuit IS
   PORT( 
      clock   : IN     std_ulogic;
      reset_N : IN     std_ulogic;
      Led2    : OUT    std_logic;
      Led3    : OUT    std_logic;
      Led4    : OUT    std_logic;
      Led5    : OUT    std_logic;
      LedOut  : OUT    std_ulogic
   );

-- Declarations

END obc_circuit ;

--
-- VHDL Architecture Board.obc_circuit.struct
--
-- Created:
--          by - student.UNKNOWN (DESKTOP-3I0F3HP)
--          at - 10:32:08 14.07.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.numeric_std.all;

LIBRARY Board;
LIBRARY OBC;

ARCHITECTURE struct OF obc_circuit IS

   -- Architecture declarations
   constant signalBitNb: positive := 16;
   constant phaseBitNb: positive := 17;
   constant stepX: positive := 2;
   constant stepY: positive := 3;

   -- Internal signal declarations
   SIGNAL logic1      : std_uLogic;
   SIGNAL reset       : std_ulogic;
   SIGNAL resetSnch_N : std_ulogic;
   SIGNAL resetSynch  : std_ulogic;


   -- Component Declarations
   COMPONENT DFF
   PORT (
      CLK : IN     std_uLogic ;
      CLR : IN     std_uLogic ;
      D   : IN     std_uLogic ;
      Q   : OUT    std_uLogic 
   );
   END COMPONENT;
   COMPONENT inverterIn
   PORT (
      in1  : IN     std_uLogic ;
      out1 : OUT    std_uLogic 
   );
   END COMPONENT;
   COMPONENT Test
   PORT (
      clock : IN     std_ulogic ;
      reset : IN     std_ulogic ;
      Led1  : OUT    std_logic ;
      Led2  : OUT    std_logic ;
      Led3  : OUT    std_logic ;
      Led4  : OUT    std_logic ;
      Led5  : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : DFF USE ENTITY Board.DFF;
   FOR ALL : Test USE ENTITY OBC.Test;
   FOR ALL : inverterIn USE ENTITY Board.inverterIn;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 4 eb4
   logic1 <= '1';


   -- Instance port mappings.
   I_dff : DFF
      PORT MAP (
         CLK => clock,
         CLR => reset,
         D   => logic1,
         Q   => resetSnch_N
      );
   I_inv1 : inverterIn
      PORT MAP (
         in1  => reset_N,
         out1 => reset
      );
   I_inv2 : inverterIn
      PORT MAP (
         in1  => resetSnch_N,
         out1 => resetSynch
      );
   I0 : Test
      PORT MAP (
         clock => clock,
         reset => resetSynch,
         Led1  => LedOut,
         Led2  => Led2,
         Led3  => Led3,
         Led4  => Led4,
         Led5  => Led5
      );

END struct;
