--
-- VHDL Architecture SPI.spiSlave.struct
--
-- Created:
--          by - silvan.zahno.UNKNOWN (WE6996)
--          at - 07:39:40 11.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.numeric_std.all;

LIBRARY gates;
  USE gates.gates.all;

LIBRARY Sequential;
LIBRARY SPI;

ARCHITECTURE struct OF spiSlave IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL out1    : std_uLogic;
   SIGNAL sClk_d  : std_uLogic;
   SIGNAL sClk_fe : std_ulogic;


   -- Component Declarations
   COMPONENT and2inv1
   GENERIC (
      delay : time := gateDelay
   );
   PORT (
      in1  : IN     std_uLogic ;
      in2  : IN     std_uLogic ;
      out1 : OUT    std_uLogic 
   );
   END COMPONENT;
   COMPONENT DFF
   GENERIC (
      delay : time := gateDelay
   );
   PORT (
      CLK : IN     std_uLogic ;
      CLR : IN     std_uLogic ;
      D   : IN     std_uLogic ;
      Q   : OUT    std_uLogic 
   );
   END COMPONENT;
   COMPONENT spiSlave_shiftreg
   GENERIC (
      spi_wbits : integer              := 8;
      spi_CPHA  : integer range 0 to 1 := 1
   );
   PORT (
      CS                : IN     std_ulogic ;
      MOSI              : IN     std_ulogic ;
      SCK_fe            : IN     std_ulogic ;
      SCK_re            : IN     std_ulogic ;
      clock_spi         : IN     std_ulogic ;
      data_i            : IN     std_ulogic_vector (spi_wbits-1 DOWNTO 0);
      data_i_valid      : IN     std_ulogic ;
      reset             : IN     std_ulogic ;
      MISO              : OUT    std_ulogic ;
      data_i_re         : OUT    std_ulogic ;
      data_o            : OUT    std_ulogic_vector (spi_wbits-1 DOWNTO 0);
      data_o_valid      : OUT    std_ulogic ;
      data_transfer_end : OUT    std_ulogic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : DFF USE ENTITY Sequential.DFF;
   FOR ALL : and2inv1 USE ENTITY Gates.and2inv1;
   FOR ALL : spiSlave_shiftreg USE ENTITY SPI.spiSlave_shiftreg;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_2 : and2inv1
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => sClk,
         in2  => sClk_d,
         out1 => out1
      );
   U_3 : and2inv1
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => sClk_d,
         in2  => sClk,
         out1 => sClk_fe
      );
   U_0 : DFF
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         CLK => clock,
         CLR => reset,
         D   => sClk,
         Q   => sClk_d
      );
   shiftreg0 : spiSlave_shiftreg
      GENERIC MAP (
         spi_wbits => 	spi_wbits				 ,
         spi_CPHA  => 	spi_CPHA				 
      )
      PORT MAP (
         CS                => CS,
         MOSI              => MOSI,
         SCK_fe            => sClk_fe,
         SCK_re            => out1,
         clock_spi         => clock,
         data_i            => tx_data,
         data_i_valid      => tx_data_valid,
         reset             => reset,
         MISO              => MISO,
         data_i_re         => tx_data_rd,
         data_o            => rx_data,
         data_o_valid      => rx_data_wr,
         data_transfer_end => data_transfer_end
      );

END struct;
