-- VHDL Entity gates.and5.symbol
--
-- Created:
--          by - francois.users (Aphelia)
--          at - 09:12:04 09/09/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.1 (Build 12)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
LIBRARY gates;
  USE gates.gates.all;

ENTITY and5 IS
   GENERIC( 
      delay : time := gateDelay
   );
   PORT( 
      in1  : IN     std_uLogic;
      in2  : IN     std_uLogic;
      in3  : IN     std_uLogic;
      in4  : IN     std_uLogic;
      in5  : IN     std_uLogic;
      out1 : OUT    std_uLogic
   );

-- Declarations

END and5 ;

