-- VHDL Entity gates.bufferUlogicVector.symbol
--
-- Created:
--          by - francois.users (Aphelia)
--          at - 09:12:02 09/09/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.1 (Build 12)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
LIBRARY gates;
  USE gates.gates.all;

ENTITY bufferUlogicVector IS
   GENERIC( 
      dataBitNb : positive := 8;
      delay     : time     := gateDelay
   );
   PORT( 
      in1  : IN     std_uLogic_vector (dataBitNb-1 DOWNTO 0);
      out1 : OUT    std_uLogic_vector (dataBitNb-1 DOWNTO 0)
   );

-- Declarations

END bufferUlogicVector ;

