-- VHDL Entity gates.demux1to4.symbol
--
-- Created:
--          by - francois.users (Aphelia)
--          at - 16:06:38 08/20/09
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.1 (Build 12)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.numeric_std.all;
LIBRARY gates;
  USE gates.gates.all;

ENTITY demux1to4 IS
   GENERIC( 
      delay : time := gateDelay
   );
   PORT( 
      in1  : IN     std_uLogic;
      sel  : IN     unsigned (1 DOWNTO 0);
      out0 : OUT    std_uLogic;
      out1 : OUT    std_uLogic;
      out2 : OUT    std_uLogic;
      out3 : OUT    std_uLogic
   );

-- Declarations

END demux1to4 ;

