-- VHDL Entity gates.logic0.symbol
--
-- Created:
--          by - Everyone.UNKNOWN (WE5450)
--          at - 11:04:46 25-Feb-10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.2 (Build 5)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
LIBRARY gates;
  USE gates.gates.all;

ENTITY logic0 IS
   PORT( 
      logic_0 : OUT    std_uLogic
   );

-- Declarations

END logic0 ;

