-- VHDL Entity gates.logic1.symbol
--
-- Created:
--          by - Everyone.UNKNOWN (WE5450)
--          at - 11:05:00 25-Feb-10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2015.2 (Build 5)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
LIBRARY gates;
  USE gates.gates.all;

ENTITY logic1 IS
   PORT( 
      logic_1 : OUT    std_uLogic
   );

-- Declarations

END logic1 ;

