-- VHDL Entity gates.mux16to1.symbol
--
-- Created:
--          by - francois.users (Aphelia)
--          at - 09:21:24 09/09/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.1 (Build 12)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.NUMERIC_STD.all;
LIBRARY gates;
  USE gates.gates.all;

ENTITY mux16to1 IS
   GENERIC( 
      delay : time := gateDelay
   );
   PORT( 
      in0    : IN     std_uLogic;
      in1    : IN     std_uLogic;
      in10   : IN     std_uLogic;
      in11   : IN     std_uLogic;
      in12   : IN     std_uLogic;
      in13   : IN     std_uLogic;
      in14   : IN     std_uLogic;
      in15   : IN     std_uLogic;
      in2    : IN     std_uLogic;
      in3    : IN     std_uLogic;
      in4    : IN     std_uLogic;
      in5    : IN     std_uLogic;
      in6    : IN     std_uLogic;
      in7    : IN     std_uLogic;
      in8    : IN     std_uLogic;
      in9    : IN     std_uLogic;
      sel    : IN     unsigned (3 DOWNTO 0);
      muxOut : OUT    std_uLogic
   );

-- Declarations

END mux16to1 ;

