-- VHDL Entity gates.mux4to1.symbol
--
-- Created:
--          by - francois.users (Aphelia)
--          at - 11:26:50 11/17/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.1 (Build 12)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.numeric_std.all;
LIBRARY gates;
  USE gates.gates.all;

ENTITY mux4to1 IS
   GENERIC( 
      dataNbBits : positive := 8;
      delay      : time     := gateDelay
   );
   PORT( 
      in0    : IN     std_ulogic;
      in1    : IN     std_ulogic;
      in2    : IN     std_ulogic;
      in3    : IN     std_ulogic;
      sel    : IN     unsigned (1 DOWNTO 0);
      muxOut : OUT    std_ulogic
   );

-- Declarations

END mux4to1 ;

