-- VHDL Entity gates.onesSigned.symbol
--
-- Created:
--          by - francois.users (Aphelia)
--          at - 16:29:34 11/11/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.1 (Build 12)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.NUMERIC_STD.all;
LIBRARY gates;
  USE gates.gates.all;

ENTITY onesSigned IS
   GENERIC( 
      dataBitNb : positive := 8
   );
   PORT( 
      ones : OUT    signed (dataBitNb-1 DOWNTO 0)
   );

-- Declarations

END onesSigned ;

