-- VHDL Entity gates.transSignedUlog.symbol
--
-- Created:
--          by - francois.francois (Aphelia)
--          at - 08:28:04 01/14/19
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.1 (Build 12)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.numeric_std.all;
LIBRARY gates;
USE gates.gates.all;

ENTITY transSignedUlog IS
   GENERIC( 
      dataBitNb : positive := 8;
      delay     : time     := gateDelay
   );
   PORT( 
      in1  : IN     signed (dataBitNb-1 DOWNTO 0);
      out1 : OUT    std_ulogic_vector (dataBitNb-1 DOWNTO 0)
   );

-- Declarations

END transSignedUlog ;

