-- VHDL Entity gates.transSignedUnsigned.symbol
--
-- Created:
--          by - francois.users (Aphelia)
--          at - 09:12:04 09/09/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.1 (Build 12)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.numeric_std.all;
LIBRARY gates;
  USE gates.gates.all;

ENTITY transSignedUnsigned IS
   GENERIC( 
      delay     : time     := gateDelay;
      dataBitNb : positive := 8
   );
   PORT( 
      in1  : IN     signed (dataBitNb-1 DOWNTO 0);
      out1 : OUT    unsigned (dataBitNb-1 DOWNTO 0)
   );

-- Declarations

END transSignedUnsigned ;

