-- VHDL Entity gates.xnor2.symbol
--
-- Created:
--          by - francois.users (Aphelia)
--          at - 14:34:42 06/09/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.1 (Build 12)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
LIBRARY gates;
  USE gates.gates.all;

ENTITY xnor2 IS
   GENERIC( 
      delay : time := gateDelay
   );
   PORT( 
      in1    : IN     std_ulogic;
      in2    : IN     std_ulogic;
      xorOut : OUT    std_ulogic
   );

-- Declarations

END xnor2 ;

