-- VHDL Entity gates.xor2.symbol
--
-- Created:
--          by - francois.users (Aphelia)
--          at - 15:29:16 08/20/09
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.1 (Build 12)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
LIBRARY gates;
  USE gates.gates.all;

ENTITY xor2 IS
   GENERIC( 
      delay : time := gateDelay
   );
   PORT( 
      in1    : IN     std_ulogic;
      in2    : IN     std_ulogic;
      xorOut : OUT    std_ulogic
   );

-- Declarations

END xor2 ;

