-- VHDL Entity gates.xor5.symbol
--
-- Created:
--          by - francois.users (Aphelia)
--          at - 15:30:22 08/20/09
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.1 (Build 12)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
LIBRARY gates;
  USE gates.gates.all;

ENTITY xor5 IS
   GENERIC( 
      delay : time := gateDelay
   );
   PORT( 
      In1    : IN     std_ulogic;
      In2    : IN     std_ulogic;
      In3    : IN     std_ulogic;
      In4    : IN     std_ulogic;
      In5    : IN     std_ulogic;
      xorOut : OUT    std_ulogic
   );

-- Declarations

END xor5 ;

